[package]
   name = "second"
   version = "0.0.1"
   description = ""

[cmake]
    include = ["cmake/OpenSSLEnv.cmake"]

#[lib]
#   name = "hm_crypt"
#   source = ["src/hm_crypt/.*"]

[[bin]]
   name = "net"
   source = ["src/ring_net.cpp", "src/hm_crypt/.*"]

[profile.dev.compiler]
    clang = "-Wdeprecated-declarations"
[profile.release.compiler]
    clang = "-Wdeprecated-declarations"

[workspace]
   member=["lib/serdepp"] 

[dependencies]
    fmt="7.1.3"
    OpenSSL="git"
    range-v3="0.11.0"
    nlohmann_json="3.9.1"
    spdlog="1.8.2"