[package]
   name = "second"
   version = "0.0.1"
   description = ""

[cmake]
    include = ["cmake/OpenSSLEnv.cmake"]

[lib]
   name = "hm_crypt"
   source = ["src/hm_crypt/.*"]

[[bin]]
   name = "net"
   source = ["src/ring_net.cpp"]

[[bin]]
   name = "net2"
   source = ["src/net2.cpp"]

[[example]]
    name = "network_client"
    source = ["examples/simnet_client.cpp"]

[[example]]
    name = "network_server"
    source = ["examples/simnet_server.cpp"]

#[profile.dev.compiler]
#    clang = "-Wno-deprecated-declarations"
#
#[profile.release.compiler]
#    clang = "-Wno-deprecated-declarations"

[dependencies]
    OpenSSL="git"
    range-v3="0.11.0"
    spdlog="1.8.2"
    RapidJSON="1.1.1"
    serdepp = "0.1.1"
    #serdepp = {version="git", branch="dev"}
    nlohmann_json="3.9.1"
